name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-php@v2
        with:
          php-version: 7.4
      - run: composer install
      - name: Deploy to GitHub Pages
        uses: peaceiris/gh-pages@v3
        with:
          target-branch: gh-pages
          publish-dir: .
